### PR TITLE
Documentation and Linting

### PR DESCRIPTION
**Pull request by cgbriggs99**
I've started writing some documentation for the code. I would appreciate some help with figuring out some of the more obscure units.

### CODE REVIEW

**Comment by jturney** [comment]
Seems odd that all this linting is needed since I use clang-format and the provided .clang-format file to set the style.

**Comment by cgbriggs99** [comment]
My bad. Undid the linting. Didn't see the formatting file.

**Comment by cgbriggs99** [comment]
That would explain why it was saying basically every line was too long.

**Comment by jturney** [comment]
Haha sounds good. Glad the linting has been resolved.

**Pull request closed without merging**
