### PR TITLE
Add codecov support

### PR DESCRIPTION
**Pull request by cgbriggs99**
Add codecov stuff, like badges.

### CODE REVIEW

**Review by jturney — COMMENTED** [review]
Is `Generate coverage html` in `coverage.yml` still needed since we're using codecov.io?

**Comment by cgbriggs99** [comment]
No, I forgot to remove it.

**Comment by jturney** [comment]
It'll be nice when this gets in.

**Comment by loriab** [comment]
Hooray! May I steal this sometime? :-)

**Comment by cgbriggs99** [comment]
It looks like the Windows job broke. I didn't change the cmake.yml file, so I don't know what caused it to break. Someone with more experience with Windows might want to check it  out.

**Comment by loriab** [comment]
Same message we've gotten over at p4. I'm suspecting a GHA windows-image error that will hopefully get fixed upstream.

**Comment by cgbriggs99** [comment]
Well, in that case I believe this pr is ready for review

**Pull request merged**
