### PR TITLE
Working on adding coverage stuff.

### PR DESCRIPTION
**Pull request by cgbriggs99**

### CODE REVIEW

**Comment by cgbriggs99** [comment]
I think this works now. It is ready for review. I'm not sure about the deployment part, though, since I'm not sure how to test it.

**Comment by cgbriggs99** [comment]
Tested, and it seems to work.

**Comment by jturney** [comment]
Let's rename `API Reference` to `Developer Guide` and move the coverage. I don't think code coverage is something that should be displayed on the main home page.

**Comment by cgbriggs99** [comment]
Fixed

**Review by jturney — APPROVED** [review]

**Pull request merged**
